version: "3.4"
services:
  giveip:
    image: ghcr.io/randomairborne/giveip
    restart: always
    networks:
      - proxy
    ports:
      - "8083:8080"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - traefik.enable=true
        - traefik.http.routers.giveip.rule=Host(`giveip.io`) || Host(`www.giveip.io`) || Host(`v4.giveip.io`) || Host(`v6.giveip.io`)
        - traefik.http.routers.giveip.entrypoints=https
        - traefik.http.routers.giveip.tls.certresolver=letsencrypt
        - traefik.http.services.giveip.loadbalancer.server.port=8083
        - traefik.http.services.giveip.loadbalancer.server.scheme=https

networks:
  proxy:
    external: true
