version: "3.4"
services:
  giveip:
    image: ghcr.io/randomairborne/giveip
    restart: always
    networks:
      - proxy
    ports:
      - "8080:8080"
    expose:
      - "8080"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.giveip.rule=Host(`giveip.io`) || Host(`www.giveip.io`) || Host(`v4.giveip.io`) || Host(`v6.giveip.io`)
        - traefik.http.routers.giveip.entrypoints=https,http
        - traefik.http.routers.giveip.tls.certresolver=letsencrypt
        - traefik.http.services.giveip.loadbalancer.server.port=8080
        - traefik.http.middlewares.giveip.headers.accesscontrolalloworiginlist=https://giveip.io,https://www.giveip.io
        - traefik.http.middlewares.giveip.headers.accesscontrolallowmethods=GET,POST,HEAD,PUT,DELETE,PATCH,OPTIONS

networks:
  proxy:
    external: true
