# fly.toml app configuration file generated for giveip-io on 2023-04-26T19:25:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "giveip-io"
primary_region = "den"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  CLIENT_IP_HEADER = "Fly-Client-IP"

[build]
  image = "ghcr.io/randomairborne/giveip:latest"

[metrics]
  port = 9090
  path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
